//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XsiBookkeeping.Web
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.HyperLink NavOverview;
        protected global::System.Web.UI.WebControls.HyperLink NavTasks;
        protected global::System.Web.UI.WebControls.HyperLink NavReport;
        protected global::System.Web.UI.WebControls.HyperLink NavAssignments;
        protected global::System.Web.UI.WebControls.HyperLink NavUsers;
        protected global::System.Web.UI.WebControls.HyperLink NavAudit;
        protected global::System.Web.UI.WebControls.Panel RoleBadgePanel;
        protected global::System.Web.UI.WebControls.Literal RoleBadgeLiteral;
        protected global::System.Web.UI.WebControls.Literal UserDisplayLiteral;
        protected global::System.Web.UI.WebControls.HyperLink LogoutLink;
    }
}
